### ISSUE TITLE
Create NimbusDatabase Entity for OfficeHour data

### ISSUE THREAD

**Issue by mfekadu** [calpoly-csai/api#116]
## Objective
Enhance the NimbusDatabase’s ability to answer questions like

```python
"What is Dr. John Smith's office hours for this quarter?"
```

Or even 

```python
"When is Dr. John Smith available this quarter?"
```

The Computer Science department office will provide us with an excel file containing the latest office hours for each professor upon email as early as the 2nd week of each academic quarter. 

## Key Result
- [x] create an Entity schema for `OfficeHour`
- [x] make sure that the `save_entity` function properly saves a new `OfficeHour`
- [ ] create a `flask_api` endpoint to `save_office_hours`

#### what the data looks like

![7FE0FD97-60F7-443E-9C1E-5FB79824424D](https://user-images.githubusercontent.com/11131250/76472170-fd677b00-63b1-11ea-92a4-f229e9d0ddda.png)

#### good points of contact
* @chidiewenike - for how the data is sourced
* @cameron-toy - for how the data is scraped
* @austinsilveria - for how the data is scraped
* @mfekadu - for any other questions

**Comment by Jason-Ku** [comment]
The "good points of contact" section is a really great inclusion!

**Comment by chidiewenike** [comment]
@mfekadu Does this Entity read in a CSV and populate the database as well? Is that what you meant by "make sure that the save_entity function properly saves a new OfficeHour"?

**Comment by mfekadu** [comment]
@chidiewenike 

The latter. `save_entity` has the job of actually persisting the data in the database.
* also, after #114 the relevant database interaction functions are called [`insert_entity`][1] and [`update_entity`][1]

A separate function to loop over a CSV and call the relevant functions (e.g. [`insert_entity`][1]) may be necessary. 

The end goal is we can do the following **POST requests**
* https://documenter.getpostman.com/view/6476483/SzS2wTS1?version=latest#737b00bc-1983-48e1-9d93-94b33f3a20c7

[1]: https://github.com/calpoly-csai/api/blob/ccd94b55648ae4e3389fc67744f60f0868fad12f/database_wrapper.py#L737

**Comment by mfekadu** [comment]
@chidiewenike @cameron-toy 

Could [`excalibur`][1] be a good manual+automated tool to help us streamline getting new data from PDFs (curricula, office hours if mistakenly provided as PDF, etc)?

Here's a [relevant article on table extraction from PDFs][2]

[1]: https://github.com/camelot-dev/excalibur/
[2]: https://hackernoon.com/an-open-source-science-tool-to-extract-tables-from-pdfs-into-excels-3ed3cc7f22e1

**Comment by chidiewenike** [comment]
@mfekadu I added the csv to the DB manually and I created a barebones office hours entity class. Is there a way to test it with our DB to ensure that it pulls the information correctly?

**Comment by mfekadu** [comment]
Awesome, thanks @chidiewenike ! Have you created a pull request yet? Sooner is better than later. 

There is an example of a database test here:

* https://github.com/calpoly-csai/api/blob/dev/tests/test_database_wrapper.py

@Jason-Ku  knows all about it.  Jason, do you have any advice for Chidi?

**Comment by Jason-Ku** [comment]
Yeah! If you want to try and save your data to a test database you could add some code in the database_wrapper.py main method to manually run save_entity. There aren't any unittests to make sure that are you Entity was made correctly yet, (I'll probably work on that tomorrow)

**Comment by cameron-toy** [comment]
@mfekadu I tried excalibur in the past for a different project and didn't have much luck with it, but success is probably dependent on how the table is represented in the PDF. It's worth a try.

**Comment by chidiewenike** [comment]
@mfekadu Where should the abstracted save_office_hours function reside? The functions for the other "save_entity" functions reside within the db instantiation of the NimbusMySQLAlchemy class. Example here:
https://github.com/calpoly-csai/api/blob/7e24774fccc6f835c59c4b6d3414b79c1ba1fd0b/flask_api.py#L120-L130
At line 129, `db.save_course(course) ` is called for each course. Since this is now universally handled by the insert_entity function, should the code I have for processing the csv be abstracted in another function?

**Comment by mfekadu** [comment]
@chidiewenike 

Feel free to just directly call the `insert_entity` function because it will work and will be simple/direct.

However, you do bring up a good point that abstracting out a `save_office_hours` function would offer better readability of the code. 

The choice is yours 😄

**Comment by chidiewenike** [comment]
@mfekadu 
Where should I store the abstracted out function? Keep it in flask_api.py or database_wrapper.py like the others?
