### ISSUE TITLE
Setup GitHub actions for running hypothesis and pytest tests

### ISSUE THREAD

**Issue by mfekadu** [calpoly-csai/api#13]
*  [GitHub actions](https://github.com/calpoly-csai/api/actions) 

*  [hypothesis](https://hypothesis.works) 

* [pytest](https://docs.pytest.org/en/latest/) 

* [marketplace for Github Actions](https://github.com/marketplace?utf8=✓&type=actions&query=pytest)

**Comment by Jason-Ku** [comment]
I believe this is done!
