### ISSUE TITLE
Empty answers for some questions

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/api#198]
**Describe the bug**
The following question produces an empty string as the response: "How would I see Dr. Ventura now?"

**To Reproduce**
1. Send a POST request to https://nimbus.api.calpolycsai.com/ask, with the payload being `{ "question": "How would I see Dr. Ventura now?"}`
2. See the following response: `{
    "answer": "",
    "session": "SOME_NEW_TOKEN"
}`

**Expected behavior**
We should get an answer, or a reason we can't answer this question.

**Comment by snekiam** [comment]
It's possible there are other questions which cause this.

**Comment by chidiewenike** [comment]
@snekiam Obtaining each step of the NLP pipeline would help answer this issue. I am curious what each step produces. 

```Input Question -> Normalized Question/Entity/Normalized Entity -> Predicted Answer -> Final Answer (Predicted Answer substituted with DB info)```

**Comment by chidiewenike** [comment]
@snekiam This dictionary should contain the contents for each step of the pipeline:
https://github.com/calpoly-csai/api/blob/671064f16ebac1cc243d5ab4556e6921efb8189f/nimbus.py#L32

**Comment by ethanahlquist** [comment]
It seems like the NPL is producing a wierd 'question class' when processing the 'normalized question':

```
{'entity': 'Dr. Ventura', 'tag': 'PROF', 'normalized entity': 'Ventura', 'input question': 'How would I see Dr. Ventura now?', 'normalized question': 'How would I see [PROF] now?', 'question class': 'How clearly does [PROF] present material?'}
```

'normalized question': 'How would I see [PROF] now?'
↓
'question class': 'How clearly does [PROF] present material?'
