### ISSUE TITLE
Add a "ClubName" column to the Clubs table in dev

### ISSUE THREAD

**Issue by danield2255** [calpoly-csai/api#34]
@mfekadu 
## Objective
Be able to identify a club by its name, not just its id

## Key Result
Commit change to the working dev database that has a Name column in the Clubs table

**Comment by mfekadu** [comment]
@danield2255 

The way to complete this objective is by **modifying code for the entity** (`Clubs` [source code](https://github.com/calpoly-csai/api/blob/mf-flask-api/Entity/Clubs.py)) to look more like (`Courses` [source code](https://github.com/calpoly-csai/api/blob/6a4d4a8ce92f2c5695a879559f41e90ec605b0fd/Entity/Courses.py)).

Then we can update the following code to have `self.Clubs = Clubs`

https://github.com/calpoly-csai/api/blob/805e520f6fccb3bc3978f3e30efa0a815c48f698/database_wrapper.py#L257-L260

Which further will allow us to automate the table creation step using the `_create_all_tables` function, which should just work once we call `__safe_create(self.Clubs)`

https://github.com/calpoly-csai/api/blob/805e520f6fccb3bc3978f3e30efa0a815c48f698/database_wrapper.py#L284-L296

https://github.com/calpoly-csai/api/blob/805e520f6fccb3bc3978f3e30efa0a815c48f698/database_wrapper.py#L295-L299

**Comment by mfekadu** [comment]
resolved by #49
