### ISSUE TITLE
Phrase Entry UI Glitch

### ISSUE THREAD

**Issue by snekiam** [calpoly-csai/api#43]
**Describe the bug**
Cursor not aligned on phrases/tokenization page on Firefox V72.0.2 on Windows 10

**To Reproduce**
1. Go to 'csai.app'
2. Click on 'quotes button at the bottom (")'
3. See misaligned cursor in box

**Expected behavior**
Cursor is aligned inside of box

**Screenshots**
![image](https://user-images.githubusercontent.com/8095061/74410500-15b59b80-4dee-11ea-86e0-29882872b697.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 72.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
Was not observed in Chrome.

**Comment by mfekadu** [comment]
hey @snekiam 

I think this bug goes here: https://github.com/calpoly-csai/csai-recorder/issues

**Comment by snekiam** [comment]
Whoops I had too many tabs open I guess.
