### ISSUE TITLE
Add API endpoint to store scraped courses

### ISSUE THREAD

**Issue by austinsilveria** [calpoly-csai/api#46]
## Objective
Add API to store scraped courses following the model of #53 .

* Useful comment: https://github.com/calpoly-csai/api/pull/53#issuecomment-590121657

## Key Result
Scraped courses are saved in database.

## Details

* Add API to accept a list of scraped courses
* Create `save_course()` function in `database_wrapper` to build `SQLAlchemy` `Courses` object and save it to the database.

**Comment by mfekadu** [comment]
# data looks like this
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/11131250/75120162-38da1980-563e-11ea-8475-b5977dafe8b1.png">

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/11131250/75120163-3e376400-563e-11ea-95c9-84ac0ebf593d.png">
