### ISSUE TITLE
save_clubs endpoint fails to save a club

### ISSUE THREAD

**Issue by mfekadu** [calpoly-csai/api#79]
**Describe the bug**
```
sqlalchemy.exc.DataError: (mysql.connector.errors.DataError) 1406 (22001): Data too long for column 'contact_phone' at row 1
[SQL: INSERT INTO `Clubs` (club_name, types, `desc`, contact_email, contact_email_2, contact_person, contact_phone, box, advisor, affiliation) VALUES (%(club_name)s, %(types)s, %(desc)s, %(contact_email)s, %(contact_email_2)s, %(contact_person)s, %(contact_phone)s, %(box)s, %(advisor)s, %(affiliation)s)]
[parameters: {'club_name': 'test_club', 'types': 'Academic, Special Interest', 'desc': 'description', 'contact_email': 'test@test.com', 'contact_email_2': 'test@test.com', 'contact_person': 'Test Person', 'contact_phone': 15552223232, 'box': 89, 'advisor': 'Test Person', 'affiliation': None}]
(Background on this error at: http://sqlalche.me/e/9h9h)

-->

========================================= 1 failed, 1 passed in 5.70s =========================================
➜  tests git:(mf-patch-and-test) ✗
```

#### discovered by new tests from #80

**Comment by mfekadu** [comment]
@austinsilveria  any clues on this bug?

**Comment by austinsilveria** [comment]
@mfekadu Looks like the `contact_phone` column in the [Clubs Entity](https://github.com/calpoly-csai/api/blob/dev/Entity/Clubs.py) is set to take a `String` with max length `10`. I didn't run into this issue when populating the table with scraped clubs, but it might be worth it to increase the size a bit for safety.

**Comment by mfekadu** [comment]
@austinsilveria , I agree. 

**What size is reasonable? Should we bother supporting all kinds of contact_phone formats or expect normalized data?**
* `12223334444` (largest USA phone length with no extension)
* `1-222-333-4444`
* `1 (222) 333-4444`
* `12223334444,,5555...5`(phone with extension, there could be up to `N` 5's such that `N=¯\_(ツ)_/¯`)

**Comment by adamperlin** [comment]
@mfekadu maybe just double the max size, for now, to be safe?

**Comment by mfekadu** [comment]
@adamperlin  @austinsilveria  okay I'll make it double in my next PR within the next few minutes

**Comment by mfekadu** [comment]
# has been fixed
https://github.com/calpoly-csai/api/blob/48336b06f95e3676c5322d6760c34968b2d145d5/Entity/Clubs.py#L17
