### ISSUE TITLE
Add to the requirements.txt

### ISSUE THREAD

**Issue by chidiewenike** [calpoly-csai/api#82]
spacy==2.2.2
nltk==3.4.5
google-cloud-automl=0.10.0
sklearn==0.0
google-cloud==0.34.0
google-cloud-speech==1.3.2

**Comment by mfekadu** [comment]
resolved by 
* https://github.com/calpoly-csai/api/commit/6c7c45a38c30be88f103c695fb0c34db035285cc

* https://github.com/calpoly-csai/api/commit/0d17a9f263172fd9c48122514197cc57191f03eb

* https://github.com/calpoly-csai/api/commit/ad3c989a49860f66e6f6fea18774ad013ba5c116
